#ifndef MVSTAB_FFMPEG_MOTION_METADATA_H
#define MVSTAB_FFMPEG_MOTION_METADATA_H

#include <stdint.h>

#define MVSTAB_AV_MV_REFERENCE_INDEX_MASK UINT64_C(0x3f)
#define MVSTAB_AV_MV_REFERENCE_LIST1 (UINT64_C(1) << 6)
#define MVSTAB_AV_MV_LONG_REFERENCE (UINT64_C(1) << 7)
#define MVSTAB_AV_MV_REFERENCE_TOP_FIELD (UINT64_C(1) << 8)
#define MVSTAB_AV_MV_REFERENCE_BOTTOM_FIELD (UINT64_C(1) << 9)
#define MVSTAB_AV_MV_DIRECT (UINT64_C(1) << 10)
#define MVSTAB_AV_MV_SKIP (UINT64_C(1) << 11)
#define MVSTAB_AV_MV_INTERLACED (UINT64_C(1) << 12)
#define MVSTAB_AV_MV_PTS_DELTA_VALID (UINT64_C(1) << 13)
#define MVSTAB_AV_MV_REFERENCE_EXACT (UINT64_C(1) << 14)
#define MVSTAB_AV_MV_PTS_DELTA_SHIFT 16
#define MVSTAB_AV_MV_PTS_DELTA_MASK UINT64_C(0x0000ffffffffffff)

#endif
